-- Create the table for AI generated recipes if it doesn't exist
CREATE TABLE IF NOT EXISTS ai_generated_recipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_profile_id text NOT NULL,
  name text,
  style text,
  recipe_data jsonb,
  created_at timestamptz DEFAULT now(),
  changed_at timestamptz DEFAULT now()
);

-- Add comments for clarity
COMMENT ON TABLE ai_generated_recipes IS 'Stores AI generated recipes.';
COMMENT ON COLUMN ai_generated_recipes.user_profile_id IS 'ID of the user profile this recipe belongs to.';

-- Add RLS policies if needed, but for now we keep it simple as we are in self-hosted mode
-- ALTER TABLE ai_generated_recipes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable all access for all users" ON ai_generated_recipes FOR ALL USING (true);
