name: brew_genius
description: AiBrewGenius – dein smarter Brau-Assistent mit OpenAI.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.0
  supabase_flutter: ^2.7.1
  file_picker: ^8.0.2
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/icon_small.png
    - prompt/rezept_basis
    - prompt/freitext_rezept_basis
    - prompt/freitext_response_template.json
    - prompt/freitext_rezept_basis2
    - prompt/freitext_response_template2.json

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#0F172A"
    theme_color: "#2563EB"
  macos:
    generate: true
  windows:
    generate: true
